### PR TITLE
Pinch zoom implementation

### PR DESCRIPTION
**Pull request by scr34m**
Basic solution for pinch zoom, few tweaks and aligning to the base code style maybe required.

### CODE REVIEW

**Comment by yguedidi** [comment]
Any news on this one? Thanks

**Comment by yguedidi** [comment]
@sachinchoolur thanks for the merge! Can we expect a release with this feature soon? :)

**Comment by sachinchoolur** [comment]
Hey @yguedidi,

I'll try to release ASAP :)

**Comment by yguedidi** [comment]
@sachinchoolur @scr34m I tried it in my project, and it looks like it doesn't work well... BTW, great work @scr34m !! :)

**Comment by scr34m** [comment]
@yguedidi what is the problem, could you describe it?

**Pull request merged**
